AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This template creates a cross-account role for comprehensive cost and resource
  optimization analysis within a sub-account. It provides read-only access to
  billing, cost management, resource configuration, and optimization services
  like Cost Explorer, Budgets, Compute Optimizer, and S3 bucket configurations,
  along with inventory data for various AWS services.

Parameters:
  BlocksExternalAccountId:
    Type: String
    Default: "503132503926"
    Description: The 12-digit AWS account ID of the Blocks external account that will be trusted.
  ExternalId:
    Type: String
    NoEcho: true
    Default: "blocks-shared-secret"
    Description: 'Shared secret required in sts:AssumeRole (set per customer if you want)'

Resources:
  BlocksSubaccountCustomReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub 'BlocksSubaccountCustomReadPolicy-${AWS::StackName}'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: CostReadOnly
            Effect: Allow
            Action:
              - ce:Get*
              - ce:List*
              - ce:Describe*
              - cost-optimization-hub:Get*
              - cost-optimization-hub:List*
            Resource: "*"
          - Sid: ReservationsReadOnly
            Effect: Allow
            Action:
              - elasticache:DescribeReserved*
              - redshift:DescribeReserved*
              - rds:DescribeReserved*
              - ec2:DescribeReserved*
            Resource: "*"
          - Sid: TrustedAdvisorReadOnly
            Effect: Allow
            Action:
              - trustedadvisor:Describe*
              - trustedadvisor:Get*
              - trustedadvisor:List*
              - support:DescribeTrustedAdvisorChecks
              - support:DescribeTrustedAdvisorCheckResult
              - support:DescribeTrustedAdvisorCheckSummaries
              - support:DescribeTrustedAdvisorCheckRefreshStatuses
              - support:RefreshTrustedAdvisorCheck
            Resource: "*"
          # - Sid: PricingGetProducts
          #   Effect: Allow
          #   Action:
          #     - pricing:Describe*
          #     - pricing:Get*
          #     - pricing:List* 
            Resource: "*"
          - Sid: Ec2ReadOnly
            Effect: Allow
            Action:
              - ec2:Describe*
              - ec2:Get*
              - ec2:List*
              - dlm:Get*
              - elasticloadbalancing:Describe*
              - autoscaling:Describe*
              - autoscaling:Get*
              - autoscaling:List*
            Resource: "*"
          - Sid: RdsReadOnly
            Effect: Allow
            Action:
              - rds:Describe*
              - rds:List*
            Resource: "*"
          - Sid: ElastiCacheReadOnly
            Effect: Allow
            Action:
              - elasticache:Describe*
              - elasticache:List*
            Resource: "*"
          - Sid: RedshiftReadOnly
            Effect: Allow
            Action:
              - redshift:Describe*
              - redshift:List*
            Resource: "*"
          - Sid: LambdaReadOnly
            Effect: Allow
            Action:
              - lambda:List*
              - lambda:Get*
            Resource: "*"
          - Sid: DynamoDbReadOnly
            Effect: Allow
            Action:
              - dynamodb:List*
              - dynamodb:Describe*
            Resource: "*"
          - Sid: S3ReadOnly
            Effect: Allow
            Action:
              - s3:List*
              - s3:GetLifecycleConfiguration
              - s3:GetBucketLocation
              - s3:GetObjectRetention
            Resource: "*"
          - Sid: EcsEksEcrReadOnly
            Effect: Allow
            Action:
              - ecs:List*
              - ecs:Describe*
              - eks:List*
              - eks:Describe*
              - ecr:DescribeRepositories
              - ecr:ListImages
              - ecr:DescribeImages
            Resource: "*"
          - Sid: CloudWatchReadOnly
            Effect: Allow
            Action:
              - cloudwatch:Describe*
              - cloudwatch:Get*
              - cloudwatch:List*
              - oam:ListSinks
              - logs:Describe*
              - logs:Get*
              - logs:List*
            Resource: "*"
          - Sid: Route53ReadOnly
            Effect: Allow
            Action:
              - route53:Get*
              - route53:List*
              - route53domains:Get*
              - route53domains:List*
            Resource: "*"
          - Sid: BackupReadOnly
            Effect: Allow
            Action:
              - backup:Describe*
              - backup:Get*
              - backup:List*
            Resource: "*"
          - Sid: AppAutoScalingReadOnly
            Effect: Allow
            Action:
              - application-autoscaling:Describe*
              - application-autoscaling:List*
              - application-autoscaling:Get*
              - autoscaling-plans:Describe*
              - autoscaling-plans:Get*
            Resource: "*"
          - Sid: ApiGwReadOnly
            Effect: Allow
            Action:
              - apigateway:GET
            Resource: "*"
          - Sid: AthenaReadOnly
            Effect: Allow
            Action:
              - athena:Get*
              - athena:List*
              - athena:BatchGet*
            Resource: "*"
          - Sid: ElasticSearchReadOnly
            Effect: Allow
            Action:
              - es:Describe*
              - es:List*
              - es:Get*
            Resource: "*"
          - Sid: WorkSpacesReadOnly
            Effect: Allow
            Action:
              - workspaces:Describe*
            Resource: "*"
          - Sid: FsxReadOnly
            Effect: Allow
            Action:
              - fsx:Describe*
              - fsx:List*
            Resource: "*"
          - Sid: EfsReadOnly
            Effect: Allow
            Action:
              - elasticfilesystem:Describe*
              - elasticfilesystem:List*
            Resource: "*"
          - Sid: AppstreamReadOnly
            Effect: Allow
            Action:
              - appstream:Describe*
              - appstream:List*
            Resource: "*"
          - Sid: EmrReadOnly
            Effect: Allow
            Action:
              - elasticmapreduce:Describe*
              - elasticmapreduce:List*
            Resource: "*"
          - Sid: SageMakerReadOnly
            Effect: Allow
            Action:
              - sagemaker:Describe*
              - sagemaker:List*
              - sagemaker:Search
            Resource: "*"
          - Sid: GlueReadOnly
            Effect: Allow
            Action:
              - Glue:Get*
              - Glue:List*
            Resource: "*"
            
  BlocksReadRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::AccountId}-Blocks-read-role'
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${BlocksExternalAccountId}:root'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalId

      ManagedPolicyArns:
        - !Ref BlocksSubaccountCustomReadPolicy
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AWSBillingReadOnlyAccess
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AWSBudgetsReadOnlyAccess
        - !Sub arn:${AWS::Partition}:iam::aws:policy/ServiceQuotasReadOnlyAccess
        - !Sub arn:${AWS::Partition}:iam::aws:policy/ComputeOptimizerReadOnlyAccess
        - !Sub arn:${AWS::Partition}:iam::aws:policy/ResourceGroupsandTagEditorReadOnlyAccess
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AWSSavingsPlansReadOnlyAccess

      Policies:
        # Identity
        - PolicyName: StsWhoami
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sts:GetCallerIdentity
                Resource: "*"

Outputs:
  BlocksReadRoleArn:
    Description: 'Cross-account role for cost and resource optimization analysis within a sub-account'
    Value: !GetAtt BlocksReadRole.Arn
  BlocksReadRoleName:
    Description: 'Name of the cross-account Blocks read role'
    Value: !Ref BlocksReadRole
