AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This template creates a cross-account role that could be assumed by Blocks for comprehensive cost and resource
  optimization analysis within a sub-account. It provides read-only access to
  billing, cost management, resource configuration, and optimization services
  like Cost Explorer, Budgets, Compute Optimizer, and S3 bucket configurations,
  along with inventory data for various AWS services.

Resources:
  BlocksCostAndReservationsReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: 'BlocksCostAndReservationsReadPolicy'
      Description: 'Used by Blocks.cloud. Must remain in place for Blocks to function correctly. Email support@blocks.cloud for assistance. Read-only access to Cost Explorer, billing, CUR, and reserved instance data for cost analysis.'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # Cost and usage analytics APIs
          # Services: Cost Explorer, Cost Optimization Hub, CUR, BCM Data Exports
          - Sid: CostAndUsageReadOnly
            Effect: Allow
            Action:
              - ce:Get*
              - ce:List*
              - ce:Describe*
              - cost-optimization-hub:Get*
              - cost-optimization-hub:List*
              - cur:Get*
              - cur:DescribeReportDefinitions
              - bcm-data-exports:GetExport
              - bcm-data-exports:ListExports
            Resource: "*"
          
          # Billing data, discounts, and credits
          # Services: AWS Billing
          - Sid: PpaAndCreditsCheck
            Effect: Allow
            Action:
              - billing:GetBillingData
              - billing:GetBillingDetails
              - billing:GetCredits
            Resource: "*"
  
          # Reserved instance inventory
          # Services: EC2, RDS, Redshift, ElastiCache
          - Sid: ReservationsReadOnly
            Effect: Allow
            Action:
              - elasticache:DescribeReserved*
              - redshift:DescribeReserved*
              - rds:DescribeReserved*
              - ec2:DescribeReserved*
            Resource: "*"


  BlocksSavingsEstimationReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: 'BlocksSavingsEstimationReadOnlyPolicy'
      Description: 'Used by Blocks.cloud. Must remain in place for Blocks to function correctly. Email support@blocks.cloud for assistance. Read-only access to configuration and usage data across compute, storage, database, and monitoring services for savings analysis.'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
  
          # Compute, scaling, and load balancing
          # Services: EC2, Auto Scaling, Application Auto Scaling, ELB, Lambda, Batch, App Runner
          - Sid: ComputeAndScalingReadOnly
            Effect: Allow
            Action:
              - ec2:Describe*
              - ec2:Get*
              - ec2:List*
              - dlm:Get*
              - elasticloadbalancing:Describe*
              - autoscaling:Describe*
              - autoscaling:Get*
              - autoscaling:List*
              - application-autoscaling:Describe*
              - application-autoscaling:List*
              - application-autoscaling:Get*
              - autoscaling-plans:Describe*
              - autoscaling-plans:Get*
              - lambda:List*
              - lambda:Get*
              - batch:Get*
              - batch:List*
              - apprunner:ListServices
              - apprunner:DescribeService
              - apprunner:ListAutoScalingConfigurations
              - apprunner:DescribeAutoScalingConfiguration
              - apprunner:ListTagsForResource
            Resource: "*"
  
          # Containers, orchestration, and build/deploy
          # Services: ECS, EKS, ECR, CodeBuild, CodePipeline
          - Sid: ContainersAndBuildReadOnly
            Effect: Allow
            Action:
              - ecs:List*
              - ecs:Describe*
              - eks:List*
              - eks:Describe*
              - ecr:DescribeRepositories
              - ecr:ListImages
              - ecr:DescribeImages
              - codebuild:ListProjects
              - codebuild:BatchGetProjects
              - codebuild:ListBuilds
              - codebuild:ListBuildsForProject
              - codebuild:ListTagsForResource
              - codepipeline:GetPipeline
              - codepipeline:ListPipelines
              - codepipeline:ListTagsForResource
            Resource: "*"
  
          # Databases and caching
          # Services: RDS, DynamoDB, DAX, Redshift, Redshift Serverless, ElastiCache, MemoryDB, Neptune, Aurora DSQL
          - Sid: DatabasesAndCachingReadOnly
            Effect: Allow
            Action:
              - rds:Describe*
              - rds:List*
              - dynamodb:List*
              - dynamodb:Describe*
              - dax:DescribeClusters
              - dax:ListTags
              - dax:DescribeDefaultParameters
              - dax:DescribeParameters
              - redshift:Describe*
              - redshift:Get*
              - redshift:List*
              - redshift-serverless:Describe*
              - redshift-serverless:List*
              - elasticache:Describe*
              - elasticache:List*
              - memorydb:Describe*
              - memorydb:List*
              - memorydb:ListTags
              - dsql:Get*
              - dsql:List*
              - neptune:DescribeDBClusters
              - neptune:DescribeDBInstances
              - neptune:DescribeDBClusterSnapshots
              - neptune:DescribeDBParameterGroups
              - neptune:DescribeDBClusterParameterGroups
              - neptune:ListTagsForResource
              - neptune-graph:GetEngineStatus
              - neptune-graph:GetGraphSummary
              - neptune-db:GetEngineStatus
              - neptune-db:GetGraphSummary
            Resource: "*"
  
          # Streaming, messaging, and analytics
          # Services: Kinesis, Kinesis Data Analytics, Firehose, Timestream, Timestream InfluxDB
          - Sid: StreamingAndAnalyticsReadOnly
            Effect: Allow
            Action:
              - timestream:List*
              - timestream:Describe*
              - timestream:ListTagsForResource
              - timestream-influxdb:Get*
              - timestream-influxdb:List*
              - kinesis:ListShards
              - kinesis:ListStreamConsumers
              - kinesis:ListStreams
              - kinesis:DescribeLimits
              - kinesis:DescribeStreamConsumer
              - kinesis:DescribeStreamSummary
              - kinesis:ListTagsForResource
              - kinesisanalytics:ListApplications
              - kinesisanalytics:DescribeApplication
              - kinesisanalytics:ListTagsForResource
              - firehose:ListDeliveryStreams
              - firehose:DescribeDeliveryStream
              - firehose:ListTagsForDeliveryStream
            Resource: "*"
  
          # AI, ML, data platforms, and dashboards
          # Services: SageMaker, Glue, Bedrock, Airflow (MWAA)
          - Sid: DataPlatformsAndAiReadOnly
            Effect: Allow
            Action:
              - sagemaker:Describe*
              - sagemaker:List*
              - sagemaker:Search
              - Glue:Get*
              - Glue:List*
              - bedrock:GetProvisionedModelThroughput
              - bedrock:ListProvisionedModelThroughputs
              - airflow:ListEnvironments
              - airflow:GetEnvironment
              - airflow:ListTagsForResource
            Resource: "*"
  
          # Storage, backup, and content delivery
          # Services: S3 (metadata only), FSx, EFS, Backup
          - Sid: StorageAndContentReadOnly
            Effect: Allow
            Action:
              - s3:List*
              - s3vectors:ListVectorBuckets
              - s3:GetLifecycleConfiguration
              - s3:GetBucketLocation
              - s3:GetObjectRetention
              - s3:GetBucketTagging
              - fsx:Describe*
              - fsx:List*
              - elasticfilesystem:Describe*
              - elasticfilesystem:List*
              - backup:Describe*
              - backup:Get*
              - backup:List*
            Resource: "*"
  
          # Networking, API management, and security edges
          # Services: API Gateway, OpenSearch / ES, WAFv2, CloudFront
          - Sid: NetworkAndEdgeReadOnly
            Effect: Allow
            Action:
              - apigateway:GET
              - es:Describe*
              - es:List*
              - es:Get*
              - wafv2:ListWebACLs
              - wafv2:GetWebACL
              - wafv2:GetWebACLForResource
              - wafv2:ListResourcesForWebACL
              - wafv2:ListTagsForResource
              - cloudfront:Get*
              - cloudfront:List*
            Resource: "*"
  
  
          # End-user compute and application streaming
          # Services: WorkSpaces, AppStream
          - Sid: EndUserServicesReadOnly
            Effect: Allow
            Action:
              - workspaces:Describe*
              - appstream:Describe*
              - appstream:List*
            Resource: "*"
  
          # Monitoring, observability, and advisory services
          # Services: CloudWatch, CloudWatch Logs, Grafana, OAM, Trusted Advisor, AWS Support
          - Sid: ObservabilityAndAdvisoryReadOnly
            Effect: Allow
            Action:
              - cloudwatch:Describe*
              - cloudwatch:Get*
              - cloudwatch:List*
              - oam:ListSinks
              - logs:Describe*
              - logs:Get*
              - logs:List*
              - grafana:ListWorkspaces
              - grafana:DescribeWorkspace
              - grafana:DescribeWorkspaceConfiguration
              - grafana:ListTagsForResource
              - trustedadvisor:Describe*
              - trustedadvisor:Get*
              - trustedadvisor:List*
              - support:DescribeTrustedAdvisorChecks
              - support:DescribeTrustedAdvisorCheckResult
              - support:DescribeTrustedAdvisorCheckSummaries
              - support:DescribeTrustedAdvisorCheckRefreshStatuses
              - support:RefreshTrustedAdvisorCheck
            Resource: "*"

  BlocksReadRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'BlocksReadRole'
      Description: 'Used by Blocks.cloud. Must remain in place for Blocks to function correctly. Email support@blocks.cloud for assistance.'
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::503132503926:role/BlocksCustomerAccessRole'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': 'blocks-shared-secret'

      ManagedPolicyArns:
        - !Ref BlocksCostAndReservationsReadPolicy
        - !Ref BlocksSavingsEstimationReadOnlyPolicy
        - !Sub arn:${AWS::Partition}:iam::aws:policy/ComputeOptimizerReadOnlyAccess
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AWSOrganizationsReadOnlyAccess
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AWSSavingsPlansReadOnlyAccess
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AWSResourceGroupsReadOnlyAccess

Outputs:
  BlocksReadRoleArn:
    Description: 'Cross-account role for cost and resource optimization analysis within a sub-account'
    Value: !GetAtt BlocksReadRole.Arn
  BlocksReadRoleName:
    Description: 'Name of the cross-account Blocks read role'
    Value: !Ref BlocksReadRole
