AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This template creates a cross-account role for comprehensive cost and resource
  optimization analysis within a sub-account. It provides read-only access to
  billing, cost management, resource configuration, and optimization services
  like Cost Explorer, Budgets, Compute Optimizer, and S3 bucket configurations,
  along with inventory data for various AWS services.

Parameters:
  BlocksExternalAccountId:
    Type: String
    Default: "503132503926"
    Description: The 12-digit AWS account ID of the Blocks external account that will be trusted.
  ExternalId:
    Type: String
    NoEcho: true
    Default: "blocks-shared-secret"
    Description: 'Shared secret required in sts:AssumeRole (set per customer if you want)'

Resources:
  BlocksSubaccountCustomReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub 'BlocksSubaccountCustomReadPolicy-${AWS::StackName}'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: CeReadAll
            Effect: Allow
            Action:
              - ce:Get*
              - ce:List*
              - ce:Describe*
            Resource: "*"
          - Sid: ReservationsFullRead
            Effect: Allow
            Action:
              - ec2:DescribeReserved*
              - elasticache:DescribeReserved*
              - redshift:DescribeReserved*
              - rds:DescribeReserved*
            Resource: "*"
          - Sid: TrustedAdvisorReadAll
            Effect: Allow
            Action:   
              - trustedadvisor:Describe*
              - trustedadvisor:Get*
              - trustedadvisor:List*
              - support:DescribeTrustedAdvisorChecks
              - support:DescribeTrustedAdvisorCheckResult
              - support:DescribeTrustedAdvisorCheckSummaries
              - support:DescribeTrustedAdvisorCheckRefreshStatuses
              - support:RefreshTrustedAdvisorCheck
            Resource: "*"
          - Sid: PricingGetProducts
            Effect: Allow
            Action:
              - pricing:Describe*
              - pricing:Get*
              - pricing:List* 
            Resource: "*"
          - Sid: Ec2DescribeAll
            Effect: Allow
            Action:
              - ec2:Describe*
              - ec2:Get*
              - ec2:List*
              - ec2:SearchTransitGatewayRoutes
              - elasticloadbalancing:Describe*
              - autoscaling:Describe*
              - autoscaling:Get*
              - autoscaling:List*
            Resource: "*"
          - Sid: RdsDescribeAll
            Effect: Allow
            Action:
              - rds:Describe*
              - rds:List*
            Resource: "*"
          - Sid: ElastiCacheDescribeAll
            Effect: Allow
            Action:
              - elasticache:Describe*
              - elasticache:List*
            Resource: "*"
          - Sid: RedshiftDescribeAll
            Effect: Allow
            Action:
              - redshift:Describe*
              - redshift:List*
            Resource: "*"
          - Sid: LambdaReadAll
            Effect: Allow
            Action:
              - lambda:List*
              - lambda:Get*
            Resource: "*"
          - Sid: DynamoDbDescribeAll
            Effect: Allow
            Action:
              - dynamodb:List*
              - dynamodb:Describe*
            Resource: "*"
          - Sid: S3ReadAccess
            Effect: Allow
            Action:
              - s3:List*
              - s3:GetBucketVersioning
              - s3:GetLifecycleConfiguration
              - s3:GetBucketLogging
              - s3:GetBucketEncryption
              - s3:GetBucketTagging
              - s3:GetBucketLocation
            Resource: "*"
          - Sid: MQReadAccess
            Effect: Allow
            Action:
             - mq:Describe*
             - mq:List*
            Resource: "*"
          - Sid: EcsEksDescribeAll
            Effect: Allow
            Action:
              - ecs:List*
              - ecs:Describe*
              - eks:List*
              - eks:Describe*
            Resource: "*"
          - Sid: CloudWatchReadAll
            Effect: Allow
            Action:
              - cloudwatch:Describe*
              - cloudwatch:Get*
              - cloudwatch:List*
              - oam:ListSinks
              - logs:Describe*
              - logs:Get*
              - logs:List*
              - logs:StartQuery
              - logs:StopQuery
              - logs:TestMetricFilter
            Resource: "*"
          - Sid: CloudTrailReadAccess
            Effect: Allow
            Action:
              - cloudtrail:CancelQuery
              - cloudtrail:Describe*
              - cloudtrail:Get*
              - cloudtrail:LookupEvents
              - cloudtrail:StartQuery
              - config:DescribeConfigurationRecorderStatus
            Resource: "*"
          - Sid: CfnDescribeAll
            Effect: Allow
            Action:
              - cloudformation:Describe*
              - cloudformation:List*
              - cloudformation:Get*
              - cloudformation:DetectStackDrift
              - cloudformation:DetectStackResourceDrift
            Resource: "*"
          - Sid: SsmReadAll
            Effect: Allow
            Action:
              - ssm:Describe*
              - ssm:Get*
              - ssm:List*
            Resource: "*"
          - Sid: ConfigDescribeAll
            Effect: Allow
            Action:
              - config:Describe*
              - config:Get*
              - config:List*
              - config:Select*
              - config:BatchGet*
            Resource: "*"
          - Sid: CloudFrontReadAll
            Effect: Allow
            Action:
              - cloudfront:Get*
              - cloudfront:List*
            Resource: "*"
          - Sid: Route53ReadAll
            Effect: Allow
            Action:
              - route53:Get*
              - route53:List*
              - route53domains:Get*
              - route53domains:List*
            Resource: "*"
          - Sid: LicenseManagerReadAll
            Effect: Allow
            Action:
              - license-manager:Get*
              - license-manager:List*
            Resource: "*"
          - Sid: BackupReadAll
            Effect: Allow
            Action:
              - backup:Describe*
              - backup:Get*
              - backup:List*
            Resource: "*"
          - Sid: HealthReadAll
            Effect: Allow
            Action:
              - health:Describe*
            Resource: "*"
          - Sid: AppAutoScalingReadAll
            Effect: Allow
            Action:
              - application-autoscaling:Describe*
            Resource: "*"
          - Sid: BeanstalkReadAll
            Effect: Allow
            Action:
              - elasticbeanstalk:Describe*
              - elasticbeanstalk:List*
            Resource: "*"
          - Sid: KinesisReadAll
            Effect: Allow
            Action:
              - kinesis:Describe*
              - kinesis:List*
              - firehose:Describe*
              - firehose:List*
              - kinesisanalytics:Describe*
              - kinesisanalytics:List*
            Resource: "*"
          - Sid: MessagingReadAll
            Effect: Allow
            Action:
              - sns:Get*
              - sns:List*
              - sqs:Get*
              - sqs:List*
            Resource: "*"
          - Sid: ApiGwReadAll
            Effect: Allow
            Action:
              - apigateway:GET
            Resource: "*"
          - Sid: StepFunctionsReadAll
            Effect: Allow
            Action:
              - states:Describe*
              - states:List*
              - states:Get*
            Resource: "*"
          - Sid: GlueReadAll
            Effect: Allow
            Action:
              - glue:Get*
              - glue:List*
              - glue:BatchGet*
            Resource: "*"
          - Sid: AthenaReadAll
            Effect: Allow
            Action:
              - athena:Get*
              - athena:List*
              - athena:BatchGet*
            Resource: "*"
          - Sid: EmrReadAll
            Effect: Allow
            Action:
              - elasticmapreduce:Describe*
              - elasticmapreduce:List*
              - elasticmapreduce:View*
              - elasticmapreduce:Get*
            Resource: "*"
          - Sid: SageMakerReadAll
            Effect: Allow
            Action:
              - sagemaker:Describe*
              - sagemaker:List*
              - sagemaker:Get*
            Resource: "*"
          - Sid: OpenSearchReadAll
            Effect: Allow
            Action:
              - es:Describe*
              - es:List*
              - es:Get*
            Resource: "*"
          - Sid: WorkSpacesReadAll
            Effect: Allow
            Action:
              - workspaces:Describe*
            Resource: "*"
          - Sid: AppStreamReadAll
            Effect: Allow
            Action:
              - appstream:Describe*
              - appstream:List*
            Resource: "*"
          - Sid: FsxReadAll
            Effect: Allow
            Action:
              - fsx:Describe*
              - fsx:List*
            Resource: "*"
          - Sid: EfsReadAll
            Effect: Allow
            Action:
              - elasticfilesystem:Describe*
              - elasticfilesystem:List*
            Resource: "*"
          - Sid: StorageGatewayReadAll
            Effect: Allow
            Action:
              - storagegateway:Describe*
              - storagegateway:List*
            Resource: "*"
          - Sid: DxReadAll
            Effect: Allow
            Action:
              - directconnect:Describe*
            Resource: "*"
          - Sid: TransferReadAll
            Effect: Allow
            Action:
              - transfer:Describe*
              - transfer:List*
            Resource: "*"
            
  BlocksBillingReadRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::AccountId}-billing-read-role'
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${BlocksExternalAccountId}:root'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalId

      ManagedPolicyArns:
        - !Ref BlocksSubaccountCustomReadPolicy
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AWSBillingReadOnlyAccess
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AWSBudgetsReadOnlyAccess
        - !Sub arn:${AWS::Partition}:iam::aws:policy/ServiceQuotasReadOnlyAccess
        - !Sub arn:${AWS::Partition}:iam::aws:policy/ComputeOptimizerReadOnlyAccess
        - !Sub arn:${AWS::Partition}:iam::aws:policy/ResourceGroupsandTagEditorReadOnlyAccess
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AWSSavingsPlansReadOnlyAccess

      Policies:
        # Identity
        - PolicyName: StsWhoami
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sts:GetCallerIdentity
                Resource: "*"

Outputs:
  BillingReadRoleArn:
    Description: 'Cross-account role for cost and resource optimization analysis within a sub-account'
    Value: !GetAtt BlocksBillingReadRole.Arn
  BillingReadRoleName:
    Description: 'Name of the cross-account billing read role'
    Value: !Ref BlocksBillingReadRole
